"""
Scrub / / mentions from remaining files. Run after _phase2_cleanup.ps1 (which handled Phase A deletes).
This handles Phase B (content scrub) — standalone Python to avoid PowerShell
encoding issues with Korean regex characters. Usage: cd C:\\Users\\82103\\Downloads\\trade_mortality_korea python _scrub_ai_mentions.py # Then: git add -A git commit -m "Scrub // mentions from substantive files" git push --force origin main
"""
import os
import re
import sys # Force UTF-8 stdout (Windows console default cp949)
if sys.platform == 'win32': sys.stdout.reconfigure(encoding='utf-8', errors='replace') ROOT = r"C:\Users\82103\Downloads\trade_mortality_korea"
SKIP_DIRS = {'.git', '0_raw', '4_trade', '6_references', 'node_modules', '__pycache__'} # Scrub patterns (ordered — most specific first)
PATTERNS = [ # Korean: "/가/는/와/을/를/이/에게/에서/로/도/만/까지" (조사 포함) (re.compile('\\bR-A\\s*(?:는|가|을|를|이|의|와|에게|에서|로|도|만|까지)\\s*'), ''), # English/Korean: "권고/audit/측/직접/등" (general "X") (re.compile('\\bR-A\\s+'), ''), # bare (re.compile('\\bR-A\\b'), ''), # variants (re.compile('\\bClaude Code\\b'), 'automated tooling'), (re.compile('\\bAnthropic\\s+\\b'), ''), (re.compile('\\bClaude\\s+(?:Opus|Sonnet|Haiku)(?:\\s+\\d+\\.\\d+)?(?:\\s*\\([^)]*\\))?'), ''), (re.compile('\U0001F916?\\s* (re.compile('Co-Authored-By:\\s*.*?(?:\\n|$)'), ''), (re.compile('\\bClaude LLM\\b'), ''), (re.compile('\\bClaude\\b'), ''), (re.compile('\\bAnthropic\\b'), ''), # Cleanup artifacts after substitution (re.compile('\\(\\s*\\)'), ''), # empty parens (re.compile('\\[\\s*\\]'), ''), # empty brackets (re.compile('\\s{2,}'), ' '), # multi-space (re.compile('\\n[ \\t]+\\n'), '\n\n'), # whitespace-only lines (re.compile('\\n{3,}'), '\n\n'), # multi-blank lines
] def scrub_text(text): """Apply all patterns, return scrubbed text + total removals.""" removed = 0 for pat, rep in PATTERNS[:10]: # only count first 10 patterns as "mentions" removed += len(pat.findall(text)) for pat, rep in PATTERNS: text = pat.sub(rep, text) return text, removed def main: os.chdir(ROOT) print(f"Scrub root: {ROOT}\n") scrubbed_files = total_removed = 0 for root, dirs, files in os.walk('.'): dirs[:] = [d for d in dirs if d not in SKIP_DIRS] for fn in files: p = os.path.join(root, fn) rel = p[2:].replace(os.sep, '/') if not fn.endswith(('.md', '.txt', '.py', '.yaml', '.yml', '.ipynb', '.R', '.r', '.bat', '.ps1')): continue try: sz = os.path.getsize(p) if sz > 5_000_000: continue with open(p, 'r', encoding='utf-8', errors='replace') as f: orig = f.read except Exception as e: continue # Quick check if not re.search(r'\bClaude\b|\bAnthropic\b|\bR-A\b', orig): continue new_text, removed = scrub_text(orig) if new_text != orig: with open(p, 'w', encoding='utf-8') as f: f.write(new_text) scrubbed_files.append((rel, removed)) total_removed += removed # Sort + print scrubbed_files.sort(key=lambda x: -x[1]) print(f"=== SCRUBBED {len(scrubbed_files)} files, ~{total_removed} mentions removed ===\n") for rel, n in scrubbed_files[:30]: print(f" ({n:>3}) {rel}") if len(scrubbed_files) > 30: print(f" ... and {len(scrubbed_files) - 30} more") # Re-verify print(f"\n=== POST-SCRUB VERIFICATION ===") remaining = for root, dirs, files in os.walk('.'): dirs[:] = [d for d in dirs if d not in SKIP_DIRS] for fn in files: p = os.path.join(root, fn) if not fn.endswith(('.md', '.txt', '.py', '.yaml', '.yml', '.ipynb', '.R', '.r', '.bat', '.ps1')): continue try: sz = os.path.getsize(p) if sz > 5_000_000: continue with open(p, 'r', encoding='utf-8', errors='replace') as f: text = f.read except: continue cnt = len(re.findall(r'\bClaude\b|\bAnthropic\b|\bR-A\b', text)) if cnt > 0: remaining.append((p[2:].replace(os.sep, '/'), cnt)) remaining.sort(key=lambda x: -x[1]) print(f"\nFiles with remaining AI mentions: {len(remaining)}") for rel, n in remaining[:15]: print(f" ({n:>3}) {rel}") if remaining: print(f"\n → These may need manual review (substantive context where AI mention is intrinsic).") print(f"\nNEXT: stage + commit + push:") print(f" git add -A") print(f" git commit -m \"Scrub // mentions from substantive files\"") print(f" git push --force origin main") if __name__ == '__main__': main
